project:
  type: book

book:
  title: "book"
  author: "Stefan Gudenkauf"
  date: "7/19/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

toc: true
toc-depth: 2
# toc-title: Contents

bibliography: references.bib

format:
  html:
    theme: cerulean
    cover-image: cover.png
  pdf:
    documentclass: scrreprt  # scrbook
    cover-image: cover.png
  epub:
    cover-image: cover.png



