project:
  type: book

book:
  title: "book"
  author: "Stefan Gudenkauf"
  date: "7/19/2024"
  search: true
  page-navigation: true
  downloads: [pdf, epub]
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  # favicon: logo.png
  # site-url: https://example.com


toc: true
toc-depth: 2
# toc-title: Contents

bibliography: references.bib

format:
  html:
    theme: simplex
    cover-image: cover.png
    code-copy: true
  pdf:
    #documentclass: scrbook
    #documentclass: scrreprt
    documentclass: book
    cover-image: cover.png
  epub:
    cover-image: cover.png

